### ISSUE TITLE
Allow content authors to set counter styles on deeply nested ordered lists

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/developer.chrome.com#4052]
## Is your feature request related to a problem? Please describe.

We would like the ability to create nested ordered lists with different styles at various levels of nesting. This formatting is common in legal and policy documents. See Additional context for examples.

## Describe the solution you'd like

Ideally, the solution we adopt would have the following properties

* Compatible with Markdown syntax for ordered lists
* Minimal syntax – should not be notably more difficult to use than HTML 3-style type attributes.
* Allows content authors to declare how nested ordered lists should behave for a given set of pages

## Describe alternatives you've considered

* Implement HTML 3-style "type" attributes (see below)
  * This approach strikes me as perhaps the most direct and actionable solution. When combined with an extra newline before/after a block of content, it also allows for Markdown rendering of content inside HTML tags.
* Allow content authors to declare & inject stylesheets on appropriately tagged classes
  * This approach may be unacceptably brittle. I explored something like this, but I declared an article class in the global stylesheet.
* Remove all ordered lists & embed section prefixes at the beginning of each paragraph as necessary
  * This approach is error prone and notably increases the maintenance burden for affected content.
* Embed style blocks in pages to manually re-style content as necessary
  * This approach is prohibitively difficult due to the way ordered lists are styled.

### Use in policy

<details><summary><strong>Steam's Privacy Policy Agreement</strong></summary>
   
![image](https://user-images.githubusercontent.com/1047763/196572255-ca98d8fa-0ef2-45ee-914a-904ebd613ba9.png)
  
https://store.steampowered.com/privacy_agreement

</details>
<details><summary><strong>Google's Privacy & Terms for Advertising</strong></summary>
    
![image](https://user-images.githubusercontent.com/1047763/196572418-1a239019-be0f-45d5-92b5-b8034421e4e0.png)
    
https://policies.google.com/technologies/ads?hl=en-US

</details>
<details><summary><strong>Apple's App Store Review Guidelines</strong></summary>

![image](https://user-images.githubusercontent.com/1047763/196577220-4a40c02a-5751-44c6-9c24-dbd36ea42d54.png)

https://developer.apple.com/app-store/review/guidelines/#design

</details>

### Use in law

<details><summary><strong>California's Constitution</strong></summary>

![image](https://user-images.githubusercontent.com/1047763/196572734-57707be1-d979-4318-bbde-297b361efaca.png)

https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CONS&division=&title=&part=&chapter=&article=I

</details>
<details><summary><strong>H.R.5376 - Inflation Reduction Act of 2022</strong></summary>

![image](https://user-images.githubusercontent.com/1047763/196572645-c95531ab-a881-4b88-b2b7-95c21b664350.png)

https://www.congress.gov/117/bills/hr5376/BILLS-117hr5376enr.pdf

</details>

### HTML 3 style type attributes

With these changes, it's possible to hand-write HTML in order to manually control the counter style of an ordered list.

<details><summary><strong><code>/site/_scss/_typography.scss</code></strong></summary>

```scss
.type {

  // ...

  // Emulate HTML 3 ordered list types.
  //
  // NOTE: The case sensitivity of CSS attribute value selectors is determined
  // by the host document. HTML 5 attributes are case insensitive, so `[type='a']`
  // will not work as desired. In order to completely emulate HTML 3 behavior, we
  // need to use case sensitive attribute matching (specified in Selectors Level 4).
  // https://www.w3.org/TR/selectors-4/#attribute-case

  ol[type='a'] {
    --ol-counter-style: lower-alpha;
  }

  ol[type='A'] {
    --ol-counter-style: upper-alpha;
  }

  // Use case sensitive matching in supporting browsers
  ol[type='a' s] {
    --ol-counter-style: lower-alpha;
  }

  ol[type='i'] {
    --ol-counter-style: lower-roman;
  }

  ol[type='I'] {
    --ol-counter-style: upper-roman;
  }

  // Use case sensitive matching in supporting browsers
  ol[type='i' s] {
    --ol-counter-style: lower-roman;
  }

  ol[type='1'] {
    --ol-counter-style: decimal;
  }

  // Follow the pattern of other typography customization and expose
  // ordered list styling controls as classes.
  &--ordered-list {
    &.decimal {
      --ol-counter-style: decimal;
    }

    &.roman-lower {
      --ol-counter-style: lower-roman;
    }

    &.roman-upper {
      --ol-counter-style: upper-roman;
    }

    &.alpha-lower {
      --ol-counter-style: lower-alpha;
    }

    &.alpha-upper {
      --ol-counter-style: upper-alpha;
    }
  }
}
```

</details>
<details><summary><strong><code>/site/_scss/globals/extends/_type.scss</code></strong></summary>

```scss
%type {
  // ...

  &--ordered-list {
    // ...

    &::before {
      // ...

      // By default the second property of counter() is <counter-style>. This
      // value cannot be set to 'inherit', so we use a custom property to
      // emulate this behavior.
      content: counter(ol-step-counter, var(--ol-counter-style, decimal));
    }
  }
}
```

</details>
<details><summary><strong>Example HTML snippet</strong></summary>

```html
<ol type="I">
  <li>Upper roman
    <ol type="A">
      <li>Upper alpha
        <ol type="1">
          <li>Decimal
            <ol type="i">
              <li>Lower roman</li>
            </ol>
          </li>
        </ol>
      </li>
    </ol>
  </li>
</ol>
```

</details>
<details><summary><strong>Rendered HTML – before</strong></summary>

![image](https://user-images.githubusercontent.com/1047763/196576464-5c3cba45-9122-4994-a9fa-b80c48b349dd.png)

</details>
<details><summary><strong>Rendered HTML – after</strong></summary>

![image](https://user-images.githubusercontent.com/1047763/196576210-a265466c-30e4-4227-96bc-aed11f5d6db9.png)

</details>
