### ISSUE TITLE
Wrong CSS rule is struck-through when !important is added to CSS rules defined in cascade layers.

### ISSUE THREAD

**Issue by canzoroglu** [GoogleChrome/developer.chrome.com#5448]
**Describe the bug**
Wrong CSS rule is crossed-out in the Styles tab when `!important` rule is applied to the CSS rules defined in cascade layers. 

**To Reproduce**
1. Two cascade layers are defined inside a style tag in an HTML document as follows:
```css
@layer base {
  h1 {
    background-color: red !important;
  }
}
@layer sec {
  h1 {
    background-color: green !important;
  }
} 
```
**Expected behavior**
According to [Cascade order](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#complete_cascade_order) `base` layer must override `sec` layer which is the case as it can be seen in the screenshot. However, in the Styles tab wrong CSS rule is struck-through. 

**Screenshots**
![image](https://user-images.githubusercontent.com/28089293/221350098-59568db6-4df2-4701-8fde-f15b798a3f34.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home 10.0.19044]
 - Browser [Chrome]
 - Version [110]
