### ISSUE TITLE
Details element is showing disclosure triangle.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#702]
@samdutton said that when he used the following code the details element showed a disclosure triangle.

```
{% Details %}
{% DetailsSummary %}
### Relevant content and ads
{% endDetailsSummary %}

* [FLoC](/docs/privacy-sandbox/floc): Ad selection for interest groups: "relevant ads". 
* [FLEDGE](/docs/privacy-sandbox/fledge): Ad selection for remarketing. Descendant of 
[TURTLEDOVE](https://github.com/WICG/turtledove).

{% endDetails %}
```

![image](https://user-images.githubusercontent.com/1066253/116293502-d6057600-a74b-11eb-94ca-f22b790f8d5e.png)

**Comment by robdodson** [comment]
on web.dev we now use code like this which may help:

```scss
summary {
  list-style: none; // this seems to be important if you're putting a div inside of the summary

  &::marker,
  &::-webkit-details-marker {
    display: none;
  }
}
```
