### ISSUE TITLE
Let posts have custom banners.

### ISSUE THREAD

**Issue by jecfish** [GoogleChrome/developer.chrome.com#843]
At the moment, I include that in the beginning of each blog post. Example: https://developer.chrome.com/blog/new-in-devtools-89

**Comment by robdodson** [comment]
This seems like something we could move into a banner (since it has a clickable call to action). This is _almost_ possible today. If you add:

```yaml
override:banner:
  type: info
  text: Hello world
  actions:
    - text: Apply
      href: https://google.com
    - text: Dismiss
```

to an existing post, it will display a custom banner just for that page. But you **should not** do this yet, because clicking anything in that banner will cause the site to "forget" any other banners that the user has previously dismissed. So I'd suggest we turn this into a feature request to make the site support multiple dismissible banners.
