### ISSUE TITLE
Docs subsections should start with an index page

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/developer.chrome.com#89]
@robdodson commented on [Fri Oct 30 2020](https://github.com/GoogleChrome/dcc-private/issues/203)

**Is your feature request related to a problem? Please describe.**

We want to ensure that authors create an index page for their subsections, here's an example where the first link in the overview section goes to an index page:

```
- title: i18n.docs.extensions.overview
  sections:
    - url: /docs/extensions/overview
    - url: /docs/extensions/overview/foo
    - url: /docs/extensions/overview/bar
```

**Describe the solution you'd like**
It would be good to have a linter that enforces this structure. Otherwise folks may end up creating subsections with empty urls.

For example, if I did this:

```
- title: i18n.docs.extensions.overview
  sections:
    - url: /docs/extensions/overview/qux
    - url: /docs/extensions/overview/foo
    - url: /docs/extensions/overview/bar
```

A user might logically go to `/docs/extensions/overview/` to see what's there, only to be greeted with a 404.
